name: 'open-resume/setup'
description: >-
  Setup node, repo, deps, build
runs:
  using: 'composite'
  steps:
    - name: 'Checkout Repository 🛎️'
      uses: 'actions/checkout@v3'
    - name: 'Use Node.js 📗'
      uses: 'actions/setup-node@v3'
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'

    - name: 'Install node modules 📥'
      uses: 'dudeofawesome/npm-install@v1'
